# builds the content of:
# * https://github.com/symplify/phpstan-rules

# inspired by https://raw.githubusercontent.com/symplify/symplify/38d5929624d0ceb47d25d97ab020d685ac7b39a5/.github/workflows/downgrade_packages.yaml

name: Downgraded Release

on:
    push:
        # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
        tags:
            - '*'

jobs:
    downgrade_release:
        runs-on: ubuntu-latest

        steps:
            -
                uses: "actions/checkout@v2"
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                # see https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
                with:
                    fetch-depth: 0

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.1
                    coverage: none

            # to have all local tools available
            -   run: composer update --no-progress --ansi

            # remove test files
            -   run: rm -rf tests stubs

            # 3. downgrade directly
            -   run: vendor/bin/rector process src --config build/config/rector-downgrade.php --ansi

            # copy metafiles to repository as well
            -   run: cp -R build/target-repository/. .
            -   run: rm -rf build .github

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"

            # publish it to local repository to new branch with a tag
            -
                name: "Commit Downgraded - tag"
                working-directory: remote-repository
                # if: "startsWith(github.ref, 'refs/tags/')"
                run: |
                    # create new tag-based branch
                    git checkout -b "release-${GITHUB_REF#refs/tags/}"
                    git add --all
                    git commit -m "${{ matrix.tools.name }} ${GITHUB_REF#refs/tags/}" -m "release downgraded version" --allow-empty
                    git push --quiet origin main

                    # @todo uncomment when everything else works to avoid many debug tags
                    # git tag ${GITHUB_REF#refs/tags/} -m "${GITHUB_REF#refs/tags/}"
                    git push --quiet origin ${GITHUB_REF#refs/tags/}
